import { FileText, Download, Clock, Shield, Crosshair, AlertTriangle, CheckCircle2, Activity } from 'lucide-react';

function formatTimestamp(ts) {
    if (!ts) return '--';
    const d = new Date(ts * 1000);
    return d.toLocaleTimeString();
}

export default function IncidentReport({ report }) {
    if (!report) return null;

    const {
        report_id,
        session_duration,
        attacker_ip,
        threat_assessment,
        mitre_attack,
        session_stats,
        timeline,
        recommendations,
    } = report;

    const riskColor = threat_assessment.overall_risk > 70 ? '#ef4444'
        : threat_assessment.overall_risk > 40 ? '#f59e0b' : '#10b981';

    const classificationColors = {
        APT: '#dc2626',
        Advanced: '#f59e0b',
        Opportunistic: '#10b981',
    };

    const downloadReport = () => {
        const lines = [
            '═══════════════════════════════════════════════════════════════',
            '                  LABYRINTH FORGE — INCIDENT REPORT           ',
            '═══════════════════════════════════════════════════════════════',
            '',
            `Report ID:        ${report_id}`,
            `Generated:        ${new Date().toISOString()}`,
            `Session Duration: ${session_duration}s`,
            `Attacker IP:      ${attacker_ip}`,
            '',
            '── THREAT ASSESSMENT ──────────────────────────────────────────',
            `Overall Risk:     ${threat_assessment.overall_risk}/100`,
            `Classification:   ${threat_assessment.classification}`,
            `Skill Level:      ${threat_assessment.skill_level}`,
            `Frustration:      ${threat_assessment.frustration_index}/100`,
            '',
            '── MITRE ATT&CK MAPPING ──────────────────────────────────────',
            `Techniques:       ${mitre_attack.techniques_observed}`,
            `Phases Reached:   ${mitre_attack.phases_reached}/7`,
            '',
        ];

        if (mitre_attack.techniques?.length) {
            lines.push('Technique ID    | Name                              | Phase');
            lines.push('─'.repeat(70));
            for (const t of mitre_attack.techniques) {
                const id = t.technique_id.padEnd(15);
                const name = t.technique_name.padEnd(35);
                lines.push(`${id} | ${name} | ${t.phase}`);
            }
            lines.push('');
        }

        lines.push('── SESSION STATISTICS ─────────────────────────────────────────');
        lines.push(`Total Commands:       ${session_stats.total_commands}`);
        lines.push(`Suspicious Commands:  ${session_stats.suspicious_commands}`);
        lines.push(`Honey Tokens Hit:     ${session_stats.honey_tokens_accessed}`);
        lines.push(`Data Exfiltrated:     ${session_stats.data_exfiltrated}`);
        lines.push('');
        lines.push('── ATTACK TIMELINE ───────────────────────────────────────────');

        if (timeline?.length) {
            for (const entry of timeline) {
                const time = formatTimestamp(entry.timestamp);
                const risk = entry.risk_score > 15 ? ' ⚠' : '  ';
                const techs = entry.techniques?.map(t => t.id).join(', ') || '-';
                lines.push(`[${time}]${risk} ${entry.command.padEnd(30)} TTPs: ${techs}`);
            }
        }

        lines.push('');
        lines.push('── RECOMMENDATIONS ───────────────────────────────────────────');
        recommendations?.forEach((r, i) => lines.push(`${i + 1}. ${r}`));
        lines.push('');
        lines.push('═══════════════════════════════════════════════════════════════');
        lines.push('Generated by Labyrinth Forge — AI-Powered Active Defense');
        lines.push('═══════════════════════════════════════════════════════════════');

        const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${report_id}_incident_report.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="glass-card overflow-hidden border-neon-amber/30 shadow-[0_0_30px_rgba(245,158,11,0.15)] animate-slide-up">
            <div className="px-4 py-3 border-b border-white/5 bg-black/30 flex items-center gap-2">
                <FileText className="w-4 h-4 text-neon-amber" />
                <span className="font-[Orbitron] text-xs font-semibold text-neon-amber tracking-wider">
                    INCIDENT REPORT
                </span>
                <span className="ml-auto font-mono text-[10px] text-gray-500">{report_id}</span>
            </div>

            <div className="p-4 space-y-4">
                {/* Risk Classification Header */}
                <div className="flex items-center gap-4 p-3 rounded-xl border"
                    style={{
                        background: `linear-gradient(135deg, ${riskColor}10, transparent)`,
                        borderColor: `${riskColor}30`,
                    }}>
                    <div className="text-center">
                        <div className="font-[Orbitron] text-3xl font-black" style={{ color: riskColor }}>
                            {threat_assessment.overall_risk}
                        </div>
                        <div className="text-[9px] font-mono text-gray-500 mt-0.5">RISK SCORE</div>
                    </div>
                    <div className="h-12 w-px bg-white/10" />
                    <div className="flex-1 grid grid-cols-3 gap-3 text-xs">
                        <div>
                            <div className="text-gray-500 text-[10px]">Classification</div>
                            <div className="font-bold" style={{ color: classificationColors[threat_assessment.classification] || '#f59e0b' }}>
                                {threat_assessment.classification}
                            </div>
                        </div>
                        <div>
                            <div className="text-gray-500 text-[10px]">Skill</div>
                            <div className="text-white font-semibold">{threat_assessment.skill_level}</div>
                        </div>
                        <div>
                            <div className="text-gray-500 text-[10px]">Duration</div>
                            <div className="text-white font-semibold">{session_duration}s</div>
                        </div>
                    </div>
                </div>

                {/* Stats Grid */}
                <div className="grid grid-cols-4 gap-2">
                    {[
                        { icon: Activity, label: 'Commands', value: session_stats.total_commands, color: '#3b82f6' },
                        { icon: AlertTriangle, label: 'Suspicious', value: session_stats.suspicious_commands, color: '#f59e0b' },
                        { icon: Crosshair, label: 'TTPs', value: mitre_attack.techniques_observed, color: '#ef4444' },
                        { icon: Shield, label: 'Tokens Hit', value: session_stats.honey_tokens_accessed, color: '#ec4899' },
                    ].map(({ icon: Icon, label, value, color }, i) => (
                        <div key={i} className="p-2 rounded-lg bg-white/[0.03] text-center">
                            <Icon className="w-4 h-4 mx-auto mb-1" style={{ color }} />
                            <div className="text-white font-bold text-sm">{value}</div>
                            <div className="text-[9px] text-gray-500 font-mono">{label}</div>
                        </div>
                    ))}
                </div>

                {/* MITRE Techniques */}
                {mitre_attack.techniques?.length > 0 && (
                    <div>
                        <div className="text-[10px] font-[Orbitron] font-bold text-neon-red tracking-wider mb-2">
                            MITRE ATT&CK TECHNIQUES
                        </div>
                        <div className="space-y-1 max-h-[120px] overflow-y-auto">
                            {mitre_attack.techniques.map((t, i) => (
                                <div key={i} className="flex items-center gap-2 text-[11px] font-mono p-1.5 rounded bg-white/[0.03]">
                                    <span className="text-neon-red font-bold shrink-0">{t.technique_id}</span>
                                    <span className="text-gray-400 flex-1 truncate">{t.technique_name}</span>
                                    <span className="text-gray-600 text-[9px]">{t.phase}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Recommendations */}
                <div>
                    <div className="text-[10px] font-[Orbitron] font-bold text-neon-cyan tracking-wider mb-2">
                        RECOMMENDATIONS
                    </div>
                    <div className="space-y-1">
                        {recommendations?.map((r, i) => (
                            <div key={i} className="flex items-start gap-2 text-[11px] p-1.5 rounded bg-white/[0.03]">
                                <CheckCircle2 className="w-3 h-3 text-neon-cyan shrink-0 mt-0.5" />
                                <span className="text-gray-300">{r}</span>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Download Button */}
                <button
                    onClick={downloadReport}
                    className="btn-neon btn-neon-green w-full flex items-center justify-center gap-2 cursor-pointer"
                >
                    <Download className="w-4 h-4" />
                    DOWNLOAD INCIDENT REPORT
                </button>
            </div>
        </div>
    );
}
